name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Установка FFmpeg
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Проверка установки FFmpeg
      - name: Verify FFmpeg installation
        run: ffmpeg -version

      # Скачивание тестовых данных
      - name: Download test data
        run: |
          mkdir -p tests/data
          wget -O tests/data/test_audio.mp3 https://raw.githubusercontent.com/Kyamal02/audio-transcription-correction/main/tests/data/test_audio.mp3
          wget -O tests/data/expected_output.txt https://raw.githubusercontent.com/Kyamal02/audio-transcription-correction/main/tests/data/expected_output.txt

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск тестов
      - name: Run tests
        run: pytest --verbose
